strong_sort:
  ecc: True              # activate camera motion compensation
  mc_lambda: 0.995       # matching with both appearance (1 - MC_LAMBDA) and motion cost
  ema_alpha: 0.9         # updates  appearance  state in  an exponential moving average manner
  max_dist: 0.2          # The matching threshold. Samples with larger distance are considered an invalid match
  max_iou_distance: 0.7  # Gating threshold. Associations with cost larger than this value are disregarded.
  max_age: 30            # Maximum number of missed misses before a track is deleted
  n_init: 3              # Number of frames that a track remains in initialization phase
  nn_budget: 100         # Maximum size of the appearance descriptors gallery
